=== cityjson/cjio/cjio/schemas/v08/cityjson.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CityJSON v0.8",
  "description": "CityJSON specifications v0.8",
  "type": "object",

  "properties": {
    "type": { "enum": ["CityJSON"] },
    "version": { 
      "type": "string",
      "pattern": "\\d.\\d"
    },
    "metadata": {
      "type": "object",
      "$ref": "metadata.json#/metadata"
    },
    "extensions": {
      "type": "object",
      "additionalProperties": { 
        "type": "string",
        "pattern": "^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\\?([^#]*))?(#(.*))?",
        "description": "the string needs to be a URI"
      }
    },
    "CityObjects": {
      "type": "object",
      "additionalProperties": {
        "oneOf": [
          { "$ref": "cityobjects.json#/CityObjectGroup" },
          { "$ref": "cityobjects.json#/Building" },
          { "$ref": "cityobjects.json#/BuildingPart" },
          { "$ref": "cityobjects.json#/BuildingInstallation" },
          { "$ref": "cityobjects.json#/Road" },
          { "$ref": "cityobjects.json#/Railway" },
          { "$ref": "cityobjects.json#/TransportSquare" },
          { "$ref": "cityobjects.json#/TINRelief" },
          { "$ref": "cityobjects.json#/WaterBody" },
          { "$ref": "cityobjects.json#/LandUse" },
          { "$ref": "cityobjects.json#/GenericCityObject" },
          { "$ref": "cityobjects.json#/CityFurniture" },
          { "$ref": "cityobjects.json#/SolitaryVegetationObject" },
          { "$ref": "cityobjects.json#/PlantCover" },
          { "$ref": "cityobjects.json#/Bridge" },
          { "$ref": "cityobjects.json#/BridgePart" },
          { "$ref": "cityobjects.json#/BridgeInstallation" },
          { "$ref": "cityobjects.json#/BridgeConstructionElement" },
          { "$ref": "cityobjects.json#/Tunnel" },
          { "$ref": "cityobjects.json#/TunnelPart" },
          { "$ref": "cityobjects.json#/TunnelInstallation" },
          { "$ref": "cityobjects.json#/ExtensionObject" }
        ]
      }
    },
    "vertices": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {"type": "number"},
        "minItems": 3,    
        "maxItems": 3
      }
    },
    "transform": {
      "type": "object",
      "properties": {
        "scale": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 3,    
          "maxItems": 3
        },
        "translate": {
          "type": "array",
          "items": {"type": "number"},
          "minItems": 3,    
          "maxItems": 3
        }
      },
      "required": ["scale", "translate"],
      "additionalProperties": false
    },
    "appearance": {
      "type": "object",
      "properties": {
        "default-theme-texture": {"type": "string"},
        "default-theme-material": {"type": "string"},
        "materials": {
          "type": "array",
          "items": {"$ref": "appearance.json#/Material"}
        },
        "textures": {
          "type": "array",
          "items": {"$ref": "appearance.json#/Texture"}
        },
        "vertices-texture": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {"type": "number"},
            "minItems": 2,    
            "maxItems": 2
          }
        }
      },
      "additionalProperties": false
    },
    "geometry-templates": {
      "type": "object",
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "oneOf": [
              {"$ref": "geomprimitives.json#/MultiPoint"},
              {"$ref": "geomprimitives.json#/MultiLineString"},
              {"$ref": "geomprimitives.json#/Solid"},
              {"$ref": "geomprimitives.json#/MultiSolid"},
              {"$ref": "geomprimitives.json#/CompositeSolid"},
              {"$ref": "geomprimitives.json#/MultiSurface"},
              {"$ref": "geomprimitives.json#/CompositeSurface"}            
            ] 
          }
        },
        "vertices-templates": {
          "type": "array",
          "items": {
            "type": "array",
            "items": { "type": "number" },
            "minItems": 3,    
            "maxItems": 3
          }
        }
      },
      "required": ["templates", "vertices-templates"],
      "additionalProperties": false
    }
  },
  "required": ["type", "version", "CityObjects", "vertices"]
}

=== cityjson/cjio/tests/data/minimal.json
{"type":"CityJSON","version":"1.1","CityObjects":{},"vertices":[],"transform":{"scale":[0.001,0.001,0.001],"translate":[9000000000.0,9000000000.0,9000000000.0]},"metadata":{"geographicalExtent":[0,0,0,0,0,0],"citymodelIdentifier":"95aa0dd4-1b84-4053-8f8d-9499819d4173","datasetReferenceDate":"2021-03-19","datasetCharacterSet":"UTF-8","datasetTopicCategory":"geoscientificInformation","distributionFormatVersion":"1.1","spatialRepresentationType":"vector","fileIdentifier":"minimal.json","metadataStandard":"ISO 19115 - Geographic Information - Metadata","metadataStandardVersion":"ISO 19115:2014(E)","metadataCharacterSet":"UTF-8","metadataDateStamp":"2021-05-18","textures":"absent","materials":"absent","cityfeatureMetadata":{},"thematicModels":[]}}

=== cityjson/cjio/tests/data/material/mt-2.json
{"type":"CityJSON","version":"1.1","CityObjects":{"NL.IMBAG.Pand.0518100001755019":{"attributes":{"dak_type":"horizontal","data_area":2.1875,"data_coverage":0.2661913335323334,"documentnummer":"VMG20179462","geconstateerd":false,"gid":1080983,"h_dak_50p":2.0309998989105225,"h_dak_70p":2.049999952316284,"h_dak_max":2.1110000610351562,"h_dak_min":1.9889999628067017,"h_maaiveld":-0.4860000014305115,"identificatie":"NL.IMBAG.Pand.0518100001755019","kas_warenhuis":false,"lod11_replace":false,"ondergronds_type":"above ground","oorspronkelijkbouwjaar":1980,"pw_actueel":"yes","pw_bron":"ahn3","reconstructie_methode":"tudelft3d-geoflow","reconstruction_skipped":false,"rmse_lod12":0.0315316803753376,"rmse_lod13":0.031793348491191864,"rmse_lod22":0.027490859851241112,"rn":1,"status":"Pand in gebruik","t_run":41.638999938964844,"val3dity_codes_lod12":"[]","val3dity_codes_lod13":"[]","val3dity_codes_lod22":"[]","voorkomenidentificatie":1},"children":["NL.IMBAG.Pand.0518100001755019-0"],"type":"Building"},"NL.IMBAG.Pand.0518100001755019-0":{"attributes":{},"geometry":[{"boundaries":[[[[0,1,2,3]],[[4,1,0,5]],[[5,0,3,6]],[[7,2,1,4]],[[6,3,2,7]],[[6,7,4,5]]]],"lod":"1.2","semantics":{"surfaces":[{"type":"GroundSurface"},{"type":"RoofSurface"},{"on_footprint_edge":true,"type":"WallSurface"},{"on_footprint_edge":false,"type":"WallSurface"}],"values":[[0,2,2,2,2,1]]},"type":"Solid","material":{"color":{"values":[[0,0,0,0,0,0]]}}}],"parents":["NL.IMBAG.Pand.0518100001755019"],"type":"BuildingPart"}},"appearance":{"materials":[{"name":"roofandground","ambientIntensity":0.2,"diffuseColor":[0.9,0.1,0.75],"emissiveColor":[0.9,0.1,0.75],"specularColor":[0.9,0.1,0.75],"shininess":0.2,"transparency":0.5,"isSmooth":false}]},"vertices":[[338198,-42589,-486],[335196,-41370,-486],[336150,-39020,-486],[339152,-40239,-486],[335196,-41370,2041],[338198,-42589,2041],[339152,-40239,2041],[336150,-39020,2041]],"transform":{"scale":[0.001,0.001,0.001],"translate":[76364.556,451840.245,0.0]},"metadata":{"geographicalExtent":[76699.752,451797.656,-0.486,76703.708,451801.225,2.041]}}

=== cityjson/cjio/tests/data/dummy/composite_solid_with_material.json
{
  "type": "CityJSON",
  "version": "1.0",
  "CityObjects": {
    "onebuilding": {
      "type": "GenericCityObject",
      "geometry": [
        {
          "type": "CompositeSolid",
          "lod": 1,
          "boundaries": [
            [
              [
                [
                  [
                    0,
                    3,
                    2,
                    1
                  ]
                ],
                [
                  [
                    4,
                    5,
                    6,
                    7
                  ]
                ],
                [
                  [
                    0,
                    1,
                    5,
                    4
                  ]
                ],
                [
                  [
                    1,
                    2,
                    6,
                    5
                  ]
                ],
                [
                  [
                    2,
                    3,
                    7,
                    6
                  ]
                ],
                [
                  [
                    3,
                    0,
                    4,
                    7
                  ]
                ]
              ]
            ],
            [
              [
                [
                  [
                    1,
                    2,
                    9,
                    8
                  ]
                ],
                [
                  [
                    5,
                    10,
                    11,
                    6
                  ]
                ],
                [
                  [
                    1,
                    8,
                    10,
                    5
                  ]
                ],
                [
                  [
                    8,
                    9,
                    11,
                    10
                  ]
                ],
                [
                  [
                    9,
                    2,
                    6,
                    11
                  ]
                ],
                [
                  [
                    2,
                    1,
                    5,
                    6
                  ]
                ]
              ]
            ]
          ],
          "material":{
                    "irradiation": {
              "values": [[[0, 0, 1, null,1,8]],[[0,1,1,2,3,4]]]
            }
          },
          "texture":{"rgbTexture":{
            "values":[[[[[0,1,1,2,3]],[[0,3,4,5,3]],[[1,4,1,6,7]],[[0,1,1,2,3]],[[0,1,1,2,3]],[[0,1,1,2,3]]]],[[[[4,1,1,2,3]],[[3,3,4,5,3]],[[2,4,1,6,7]],[[1,1,1,2,3]],[[0,1,1,2,3]],[[10,1,1,2,3]]]]]}
          }
        }
      ]
    }
  },
  "vertices": [
    [
      0.0,
      0.0,
      0.0
    ],
    [
      1.0,
      0.0,
      0.0
    ],
    [
      1.0,
      1.0,
      0.0
    ],
    [
      0.0,
      1.0,
      0.0
    ],
    [
      0.0,
      0.0,
      1.0
    ],
    [
      1.0,
      0.0,
      1.0
    ],
    [
      1.0,
      1.0,
      1.0
    ],
    [
      0.0,
      1.0,
      1.0
    ],
    [
      2.0,
      0.0,
      0.0
    ],
    [
      2.0,
      1.0,
      0.0
    ],
    [
      2.0,
      0.0,
      1.0
    ],
    [
      2.0,
      1.0,
      1.0
    ]
  ]
}

=== cityjson/cjio/msolid.json
{
  "CityObjects": {
    "id-1": {
      "geometry": [
        {
          "boundaries": [
            [
              [
                [
                  [
                    0,
                    3,
                    2,
                    1
                  ]
                ],
                [
                  [
                    4,
                    5,
                    6,
                    7
                  ]
                ],
                [
                  [
                    0,
                    1,
                    5,
                    4
                  ]
                ],
                [
                  [
                    1,
                    2,
                    6,
                    5
                  ]
                ],
                [
                  [
                    2,
                    3,
                    7,
                    6
                  ]
                ],
                [
                  [
                    3,
                    0,
                    4,
                    7
                  ]
                ]
              ]
            ],
            [
              [
                [
                  [
                    8,
                    11,
                    10,
                    9
                  ]
                ],
                [
                  [
                    12,
                    13,
                    14,
                    15
                  ]
                ],
                [
                  [
                    8,
                    9,
                    13,
                    12
                  ]
                ],
                [
                  [
                    9,
                    10,
                    14,
                    13
                  ]
                ],
                [
                  [
                    10,
                    11,
                    15,
                    14
                  ]
                ],
                [
                  [
                    11,
                    8,
                    12,
                    15
                  ]
                ]
              ]
            ]
          ],
          "type": "MultiSolid",
          "lod": 1
        }
      ],
      "type": "GenericCityObject"
    }
  },
  "type": "CityJSON",
  "version": "1.0",
  "vertices": [
    [
      0.0,
      0.0,
      0.0
    ],
    [
      1.0,
      0.0,
      0.0
    ],
    [
      1.0,
      1.0,
      0.0
    ],
    [
      0.0,
      1.0,
      0.0
    ],
    [
      0.0,
      0.0,
      1.0
    ],
    [
      1.0,
      0.0,
      1.0
    ],
    [
      1.0,
      1.0,
      1.0
    ],
    [
      0.0,
      1.0,
      1.0
    ],
    [
      0.0,
      0.0,
      2.0
    ],
    [
      1.0,
      0.0,
      2.0
    ],
    [
      1.0,
      1.0,
      2.0
    ],
    [
      0.0,
      1.0,
      2.0
    ],
    [
      0.0,
      0.0,
      3.0
    ],
    [
      1.0,
      0.0,
      3.0
    ],
    [
      1.0,
      1.0,
      3.0
    ],
    [
      0.0,
      1.0,
      3.0
    ]
  ]
}

=== cityjson/cjio/tests/data/cube.c.json
{"CityObjects":{"id-1":{"geometry":[{"boundaries":[[[[0,1,2,3]],[[4,5,6,7]],[[0,3,5,4]],[[3,2,6,5]],[[2,1,7,6]],[[1,0,4,7]]]],"type":"Solid","lod":"1"}],"type":"+GenericCityObject"}},"version":"1.1","type":"CityJSON","vertices":[[0,0,0],[0,1000,0],[1000,1000,0],[1000,0,0],[0,0,1000],[1000,0,1000],[1000,1000,1000],[0,1000,1000]],"metadata":{"geographicalExtent":[0.0,0.0,0.0,1.0,1.0,1.0],"citymodelIdentifier":"61275d4f-079c-4dc5-a8a4-fd08a97c50a9","datasetReferenceDate":"2021-03-19","datasetCharacterSet":"UTF-8","datasetTopicCategory":"geoscientificInformation","distributionFormatVersion":"1.1","spatialRepresentationType":"vector","fileIdentifier":"cube.c.json","metadataStandard":"ISO 19115 - Geographic Information - Metadata","metadataStandardVersion":"ISO 19115:2014(E)","metadataCharacterSet":"UTF-8","metadataDateStamp":"2021-05-18","textures":"absent","materials":"absent","cityfeatureMetadata":{"+GenericCityObject":{"uniqueFeatureCount":1,"aggregateFeatureCount":1,"presentLoDs":{"1":1}}},"presentLoDs":{"1":1},"thematicModels":["+GenericCityObject"]},"transform":{"scale":[0.001,0.001,0.001],"translate":[0.0,0.0,0.0]}}

=== cityjson/cjio/tests/data/delft_1b.json
{"type":"CityJSON","version":"1.1","CityObjects":{"b1105d28c-00ba-11e6-b420-2bdcc4ab5d7f":{"attributes":{"bgt_status":"bestaand","bronhouder":"G0503","creationdate":"2014-07-09","eindregistratie":"","hoek":"(1:-52.4)","identificatiebagpnd":"503100000000035","identificatiebagvbohoogstehuisnummer":"","identificatiebagvbolaagstehuisnummer":"(1:503010000027121)","inonderzoek":"0","lokaalid":"G0503.032e68eff7ec49cce0532ee22091b28c","lv_publicatiedatum":"2016-04-12T11:54:23.000","measuredHeight":6.0,"min-height-surface":-0.100000001490116,"namespace":"NL.IMGeo","plaatsingspunt":"(1:85012.966 447473.243)","plus_status":"geenWaarde","relatievehoogteligging":"0","tekst":"(1:6)","terminationdate":"","tijdstipregistratie":"2016-03-15T12:02:49.000"},"geometry":[{"boundaries":[[[[0,1,2]],[[3,4,0]],[[5,6,7]],[[8,9,10]],[[8,11,12]],[[8,13,9]],[[5,7,14]],[[13,15,16]],[[17,13,12]],[[12,13,8]],[[18,15,19]],[[19,15,17]],[[19,17,20]],[[15,13,17]],[[6,21,22]],[[23,24,22]],[[24,25,26]],[[25,24,27]],[[28,25,27]],[[27,24,23]],[[29,27,23]],[[30,31,23]],[[23,22,21]],[[32,31,33]],[[34,32,35]],[[36,34,37]],[[37,34,35]],[[38,37,35]],[[35,32,39]],[[40,35,39]],[[41,40,39]],[[42,41,39]],[[39,32,33]],[[43,39,44]],[[44,39,45]],[[46,44,45]],[[47,46,48]],[[48,46,45]],[[45,39,49]],[[49,39,33]],[[33,31,50]],[[51,33,52]],[[52,33,50]],[[50,31,53]],[[53,31,30]],[[6,22,12]],[[3,0,14]],[[54,55,56]],[[54,30,21]],[[54,21,55]],[[30,23,21]],[[11,6,12]],[[11,7,6]],[[4,1,0]],[[5,14,0]],[[57,2,58]],[[59,2,57]],[[60,59,57]],[[60,57,61]],[[58,2,62]],[[63,58,64]],[[64,58,65]],[[66,64,65]],[[67,68,69]],[[65,67,70]],[[70,67,69]],[[69,68,71]],[[58,62,65]],[[65,72,67]],[[73,72,62]],[[72,73,74]],[[74,73,75]],[[72,65,62]],[[73,62,76]],[[2,1,62]],[[77,78,4]],[[4,78,1]],[[79,77,3]],[[3,77,4]],[[80,79,14]],[[14,79,3]],[[81,80,7]],[[7,80,14]],[[82,81,11]],[[11,81,7]],[[83,82,8]],[[8,82,11]],[[84,83,10]],[[10,83,8]],[[85,84,9]],[[9,84,10]],[[86,85,13]],[[13,85,9]],[[87,86,16]],[[16,86,13]],[[88,87,15]],[[15,87,16]],[[89,88,18]],[[18,88,15]],[[90,89,19]],[[19,89,18]],[[91,90,20]],[[20,90,19]],[[92,91,17]],[[17,91,20]],[[93,92,12]],[[12,92,17]],[[94,93,22]],[[22,93,12]],[[95,94,24]],[[24,94,22]],[[96,95,26]],[[26,95,24]],[[97,96,25]],[[25,96,26]],[[98,97,28]],[[28,97,25]],[[99,98,27]],[[27,98,28]],[[100,99,29]],[[29,99,27]],[[101,100,23]],[[23,100,29]],[[102,101,31]],[[31,101,23]],[[103,102,32]],[[32,102,31]],[[104,103,34]],[[34,103,32]],[[105,104,36]],[[36,104,34]],[[106,105,37]],[[37,105,36]],[[107,106,38]],[[38,106,37]],[[108,107,35]],[[35,107,38]],[[109,108,40]],[[40,108,35]],[[110,109,41]],[[41,109,40]],[[111,110,42]],[[42,110,41]],[[112,111,39]],[[39,111,42]],[[113,112,43]],[[43,112,39]],[[114,113,44]],[[44,113,43]],[[115,114,46]],[[46,114,44]],[[116,115,47]],[[47,115,46]],[[117,116,48]],[[48,116,47]],[[118,117,45]],[[45,117,48]],[[119,118,49]],[[49,118,45]],[[120,119,33]],[[33,119,49]],[[121,120,51]],[[51,120,33]],[[122,121,52]],[[52,121,51]],[[123,122,50]],[[50,122,52]],[[124,123,53]],[[53,123,50]],[[125,124,30]],[[30,124,53]],[[126,125,54]],[[54,125,30]],[[127,126,56]],[[56,126,54]],[[128,127,55]],[[55,127,56]],[[129,128,21]],[[21,128,55]],[[130,129,6]],[[6,129,21]],[[131,130,5]],[[5,130,6]],[[132,131,0]],[[0,131,5]],[[133,132,2]],[[2,132,0]],[[134,133,59]],[[59,133,2]],[[135,134,60]],[[60,134,59]],[[136,135,61]],[[61,135,60]],[[137,136,57]],[[57,136,61]],[[138,137,58]],[[58,137,57]],[[139,138,63]],[[63,138,58]],[[140,139,64]],[[64,139,63]],[[141,140,66]],[[66,140,64]],[[142,141,65]],[[65,141,66]],[[143,142,70]],[[70,142,65]],[[144,143,69]],[[69,143,70]],[[145,144,71]],[[71,144,69]],[[146,145,68]],[[68,145,71]],[[147,146,67]],[[67,146,68]],[[148,147,72]],[[72,147,67]],[[149,148,74]],[[74,148,72]],[[150,149,75]],[[75,149,74]],[[151,150,73]],[[73,150,75]],[[152,151,76]],[[76,151,73]],[[153,152,62]],[[62,152,76]],[[78,153,1]],[[1,153,62]]]],"lod":"1","type":"Solid"}],"type":"Building"}},"vertices":[[26518,19013,6100],[49272,20639,6100],[57336,40945,6100],[38163,12806,6100],[39145,13499,6100],[26355,18898,6100],[22390,16076,6100],[32181,8588,6100],[31078,6444,6100],[29186,47,6100],[29369,0,6100],[31367,7532,6100],[19781,3963,6100],[22749,1702,6100],[33059,9207,6100],[19449,2116,6100],[22637,1276,6100],[19414,2570,6100],[19131,2200,6100],[19182,2394,6100],[19240,2616,6100],[21097,17844,6100],[16883,4726,6100],[13197,4219,6100],[16516,3334,6100],[16632,3066,6100],[16690,3288,6100],[16272,2954,6100],[16581,2872,6100],[13084,3794,6100],[18537,20988,6100],[6817,5890,6100],[6807,5860,6100],[6391,5567,6100],[6795,5830,6100],[6727,5723,6100],[6781,5802,6100],[6765,5774,6100],[6747,5748,6100],[6632,5639,6100],[6705,5700,6100],[6682,5678,6100],[6658,5658,6100],[6604,5623,6100],[6576,5609,6100],[6454,5572,6100],[6547,5596,6100],[6516,5586,6100],[6486,5578,6100],[6423,5569,6100],[6296,5577,6100],[6359,5568,6100],[6327,5572,6100],[0,7244,6100],[18706,21113,6100],[22293,18731,6100],[19902,22000,6100],[60376,42626,6100],[62143,40097,6100],[60093,42805,6100],[60913,43391,6100],[61096,43129,6100],[57116,26169,6100],[62863,40600,6100],[63046,40338,6100],[67167,35574,6100],[63595,40712,6100],[72164,26398,6100],[72303,26207,6100],[73176,26930,6100],[73056,27103,6100],[73216,26873,6100],[66173,22180,6100],[65052,21349,6100],[66461,21771,6100],[65320,20968,6100],[62020,19214,6100],[39145,13499,0],[49272,20639,0],[38163,12806,0],[33059,9207,0],[32181,8588,0],[31367,7532,0],[31078,6444,0],[29369,0,0],[29186,47,0],[22749,1702,0],[22637,1276,0],[19449,2116,0],[19131,2200,0],[19182,2394,0],[19240,2616,0],[19414,2570,0],[19781,3963,0],[16883,4726,0],[16516,3334,0],[16690,3288,0],[16632,3066,0],[16581,2872,0],[16272,2954,0],[13084,3794,0],[13197,4219,0],[6817,5890,0],[6807,5860,0],[6795,5830,0],[6781,5802,0],[6765,5774,0],[6747,5748,0],[6727,5723,0],[6705,5700,0],[6682,5678,0],[6658,5658,0],[6632,5639,0],[6604,5623,0],[6576,5609,0],[6547,5596,0],[6516,5586,0],[6486,5578,0],[6454,5572,0],[6423,5569,0],[6391,5567,0],[6359,5568,0],[6327,5572,0],[6296,5577,0],[0,7244,0],[18537,20988,0],[18706,21113,0],[19902,22000,0],[22293,18731,0],[21097,17844,0],[22390,16076,0],[26355,18898,0],[26518,19013,0],[57336,40945,0],[60093,42805,0],[60913,43391,0],[61096,43129,0],[60376,42626,0],[62143,40097,0],[62863,40600,0],[63046,40338,0],[63595,40712,0],[67167,35574,0],[73056,27103,0],[73176,26930,0],[73216,26873,0],[72303,26207,0],[72164,26398,0],[66173,22180,0],[66461,21771,0],[65320,20968,0],[65052,21349,0],[62020,19214,0],[57116,26169,0]],"metadata":{"geographicalExtent":[84983.297,447463.655,-0.1,85056.513,447507.04600000003,6.000000000000001],"referenceSystem":"urn:ogc:def:crs:EPSG::7415","citymodelIdentifier":"ed26bd74-359b-417f-95af-28a3c9c8b7bd","datasetReferenceDate":"2021-03-19","datasetCharacterSet":"UTF-8","datasetTopicCategory":"geoscientificInformation","distributionFormatVersion":"1.1","spatialRepresentationType":"vector","fileIdentifier":"delft_1b.json","metadataStandard":"ISO 19115 - Geographic Information - Metadata","metadataStandardVersion":"ISO 19115:2014(E)","metadataCharacterSet":"UTF-8","metadataDateStamp":"2021-05-18","textures":"absent","materials":"absent","cityfeatureMetadata":{"Building":{"uniqueFeatureCount":1,"aggregateFeatureCount":1,"presentLoDs":{"1":1}}},"presentLoDs":{"1":1},"thematicModels":["Building"]},"transform":{"scale":[0.001,0.001,0.001],"translate":[84983.297,447463.655,-0.1]}}

=== cityjson/cjio/tests/data/rotterdam/rotterdam_one.json
{"type":"CityJSON","version":"1.1","CityObjects":{"{CD98680D-A8DD-4106-A18E-15EE2A908D75}":{"type":"Building","attributes":{"TerrainHeight":2.93,"bron_tex":"UltraCAM-X 10cm juni 2008","voll_tex":"complete","bron_geo":"Lidar 15-30 punten - nov. 2008","status":"1"},"geometry":[{"type":"MultiSurface","boundaries":[[[0,1,2,3,4,5,6]],[[7,8,8,9,10]],[[11,12,13,14]],[[15,16,17,18]],[[1,0,19,15]],[[0,6,20,19]],[[6,5,12,11]],[[5,4,13,12]],[[3,2,7,10]],[[2,1,21,22]],[[9,8,18,17]],[[8,8,18,18]],[[8,7,23,24]],[[11,14,16,20]]],"semantics":{"values":[0,0,0,1,2,2,2,2,2,2,2,2,2,2],"surfaces":[{"type":"RoofSurface"},{"type":"GroundSurface"},{"type":"WallSurface"}]},"texture":{"rgbTexture":{"values":[[[0,0,1,2,3,4,5,6]],[[1,7,8,8,9,10]],[[2,11,12,13,14]],[[null]],[[1,15,16,17,18]],[[1,19,20,21,22]],[[3,23,24,25,26]],[[2,27,28,29,30]],[[1,31,32,33,34]],[[2,35,36,37,38]],[[4,39,40,41,42]],[[5,43,43,44,44]],[[3,45,46,47,48]],[[4,49,50,51,52]]]}},"lod":"2"}]}},"vertices":[[524038,209058,15311],[523657,208741,15311],[527714,203869,15311],[532519,207703,15311],[529417,211476,15311],[525121,207919,15311],[524122,209126,15311],[527714,203869,11136],[529970,201158,11136],[534759,204979,11136],[532519,207703,11136],[524122,209126,12869],[525121,207919,12869],[529417,211476,12869],[528421,212688,12869],[523657,208741,0],[528421,212688,0],[534759,204979,0],[529970,201158,0],[524038,209058,0],[524122,209126,0],[523657,208741,15151],[527714,203869,15151],[527714,203869,10976],[529970,201158,10976]],"transform":{"scale":[0.001,0.001,0.001],"translate":[90409.32,435440.44,0.0]},"appearance":{"textures":[{"type":"JPG","image":"appearances/0320_4_15.jpg"},{"type":"JPG","image":"appearances/0320_4_16.jpg"},{"type":"JPG","image":"appearances/0320_4_18.jpg"},{"type":"JPG","image":"appearances/0320_4_19.jpg"},{"type":"JPG","image":"appearances/0320_4_13.jpg"},{"type":"JPG","image":"appearances/0320_4_17.jpg"}],"vertices-texture":[[0.033,0.8854],[0.0372,0.8803],[0.1023,0.9349],[0.0507,0.9991],[0.0003,0.9573],[0.0482,0.9],[0.0321,0.8865],[0.314,0.3067],[0.2779,0.2764],[0.3291,0.2126],[0.3654,0.2427],[0.2542,0.25],[0.2703,0.2634],[0.2225,0.3206],[0.2064,0.3073],[0.455,0.0706],[0.4507,0.0756],[0.3687,0.0328],[0.3729,0.0279],[0.8032,0.3657],[0.8023,0.3668],[0.7203,0.3239],[0.7212,0.3228],[0.6559,0.4971],[0.6721,0.5104],[0.6587,0.5213],[0.6426,0.508],[0.5318,0.9429],[0.4835,0.9991],[0.4704,0.992],[0.5186,0.9359],[0.9671,0.1619],[0.9159,0.2256],[0.8889,0.222],[0.9399,0.1584],[0.1395,0.0753],[0.2038,0.1301],[0.2028,0.1305],[0.1385,0.0758],[0.1218,0.8882],[0.071,0.9515],[0.0,0.9421],[0.0504,0.8794],[0.7683,0.9476],[0.6973,0.9382],[0.4918,0.2573],[0.5275,0.2877],[0.5265,0.2881],[0.4908,0.2578],[0.4863,0.3843],[0.4381,0.4404],[0.3698,0.4039],[0.4175,0.3483]]},"metadata":{"referenceSystem":"urn:ogc:def:crs:EPSG::28992","geographicalExtent":[90932.97700000001,435641.598,0.0,90944.07900000001,435653.128,15.311],"citymodelIdentifier":"c8d5f7d1-393d-4539-a52c-efaf3694090d","datasetReferenceDate":"2021-03-19","datasetCharacterSet":"UTF-8","datasetTopicCategory":"geoscientificInformation","distributionFormatVersion":"1.1","spatialRepresentationType":"vector","fileIdentifier":"rotterdam_one.json","metadataStandard":"ISO 19115 - Geographic Information - Metadata","metadataStandardVersion":"ISO 19115:2014(E)","metadataCharacterSet":"UTF-8","metadataDateStamp":"2021-05-18","textures":"present","materials":"absent","cityfeatureMetadata":{"Building":{"uniqueFeatureCount":1,"aggregateFeatureCount":1,"presentLoDs":{"2":1}}},"presentLoDs":{"2":1},"thematicModels":["Building"]}}

=== cityjson/cjio/tests/data/dummy/rectangle.json
{
    "CityObjects":
    {
        "id-1":
        {
            "geometry":
            [
                {
                    "boundaries":
                    [
                        [
                            [
                                0,
                                1,
                                2,
                                3
                            ]
                        ]
                    ],
                    "type": "MultiSurface",
                    "lod": "1.0"
                }
            ],
            "type": "Building"
        }
    },
    "version": "1.1",
    "type": "CityJSON",
    "vertices":
    [
        [
            0,
            0,
            0
        ],
        [
            0,
            1000,
            0
        ],
        [
            1000,
            1000,
            0
        ],
        [
            1000,
            0,
            0
        ]
    ],
    "metadata":
    {
        "geographicalExtent":
        [
            0.0,
            0.0,
            0.0,
            1.0,
            1.0,
            0.0
        ]
    },
    "transform":
    {
        "scale":
        [
            0.001,
            0.001,
            0.001
        ],
        "translate":
        [
            0.0,
            0.0,
            0.0
        ]
    }
}
